-- SETUP PRINCIPALS: Security Schema, Logins, and Database Users

USE BankingDWH;
GO

CREATE SCHEMA Security;
GO

USE master;
GO

CREATE LOGIN LauraGomez WITH PASSWORD = 'REDACTED', CHECK_POLICY = OFF;
CREATE LOGIN CarlosMendez WITH PASSWORD = 'REDACTED', CHECK_POLICY = OFF;
CREATE LOGIN AuditCompliance WITH PASSWORD = 'REDACTED', CHECK_POLICY = OFF;
CREATE LOGIN DWHAdmin WITH PASSWORD = 'REDACTED', CHECK_POLICY = OFF;
CREATE LOGIN ETLService WITH PASSWORD = 'REDACTED', CHECK_POLICY = OFF;
GO

USE BankingDWH;
GO

CREATE USER LauraGomez FOR LOGIN LauraGomez;
CREATE USER CarlosMendez FOR LOGIN CarlosMendez;
CREATE USER AuditCompliance FOR LOGIN AuditCompliance;
CREATE USER DWHAdmin FOR LOGIN DWHAdmin;
CREATE USER ETLService FOR LOGIN ETLService;
GO