USE master;
GO


CREATE LOGIN LauraGomez WITH PASSWORD = '<P@SSWORD>', CHECK_POLICY = OFF;
CREATE LOGIN CarlosMendez WITH PASSWORD = '<P@SSWORD>', CHECK_POLICY = OFF;
CREATE LOGIN AuditCompliance WITH PASSWORD = '<P@SSWORD>', CHECK_POLICY = OFF;
CREATE LOGIN DWHAdmin WITH PASSWORD = '<P@SSWORD>', CHECK_POLICY = OFF;
CREATE LOGIN ETLService WITH PASSWORD = '<P@SSWORD>', CHECK_POLICY = OFF;
GO

USE BankingDWH;
GO

CREATE SCHEMA Security;
GO

CREATE USER LauraGomez FOR LOGIN LauraGomez;
CREATE USER CarlosMendez FOR LOGIN CarlosMendez;
CREATE USER AuditCompliance FOR LOGIN AuditCompliance;
CREATE USER DWHAdmin FOR LOGIN DWHAdmin;
CREATE USER ETLService FOR LOGIN ETLService;
GO