-- ============================================================
-- test_audit.sql
-- Validates Native Auditing
-- 1. Generates activity
-- 2. Loads logs
-- 3. Checks that events are captured
-- ============================================================

USE BankingDWH;
GO

SET NOCOUNT ON;

DECLARE @PassCount INT = 0;
DECLARE @FailCount INT = 0;

-- Step 1: Generate activity
EXECUTE AS USER = 'LauraGomez';
SELECT TOP 1 * FROM dbo.FACT_Transaction;
SELECT TOP 1 * FROM dbo.DIM_Customer;
REVERT;

PRINT '✅ Activity generated by LauraGomez.';

-- Step 2: Load audit logs
EXEC Security.sp_LoadAuditLog;

-- Step 3: Check that events exist for LauraGomez
DECLARE @LauraEvents INT = (
    SELECT COUNT(*)
    FROM Security.AuditLog
    WHERE server_principal_name = 'LauraGomez'
      AND object_name IN ('FACT_Transaction', 'DIM_Customer')
      AND action_id = 'SL'
);

IF @LauraEvents > 0
    PRINT '✅ PASS: Audit captured ' + CAST(@LauraEvents AS NVARCHAR(10)) + ' events for LauraGomez.';
ELSE
    PRINT '❌ FAIL: No audit events found for LauraGomez.';

PRINT '========================================';
PRINT 'Audit Test: Completed.';
PRINT '========================================';
GO